apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    name: backend
    project: expense
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: backend
      project: expense
      app: backend
  template:
    metadata:
      labels:
        name: backend
        project: expense
        app: backend
    spec:
      containers:
      - name: backend
        image: promptforai/backend:v1
        envFrom:
        - configMapRef:
            name: backend
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: expense
spec:
  selector:
    name: backend
    project: expense
    app: backend
  ports:
  - name: backend-svc-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
